const userNames = [
  "draconisgaladriel",
  "animagusguldur",
  "triwizardkili",
  "beatermoria",
  "muggleithil",
  "bagshotmidgewater",
  "durmstrangperegrin",
  "mostafamearas",
  "twiggerlegolas",
  "fwoopergondor",
  "wormtailbifur",
  "mimsydain",
  "zonkoerebor",
  "acciomorgul",
  "hedwigmallorn",
  "owlsorodruin",
  "prongshollin",
  "nimbusfeanor",
  "hussanpalantir",
  "aragogringbearer",
  "marvolobeorning",
  "goylehobbiton",
  "remusdunedain",
  "basiliskdori",
  "adalbertsmaug",
  "expectohuorn",
  "portkeyorc",
  "mcgonagallbelfalas",
  "bluebottlebombur",
  "pettigrewelrond",
  "dumbledorelebennin",
  "imperiobregalad",
  "boggartweathertop",
  "devilsminhiriath",
  "ludosamwise",
  "ravenclawsmeagol",
  "phyllidameriadoc",
  "griphookaglarond",
  "crabbewormtongue",
  "cruciatusathelas",
  "hogsmeadbalrog",
  "dobbybree",
  "malkinsdwalin",
  "sherbertnori",
  "keeperriddermark",
  "seekersancho",
  "forrestfaramir",
  "pomfreyglorfindel",
  "ollivandernimrais",
  "quirrellgorgoroth",
];

const thoughts = [
  "I love the smell of napalm in the morning",
  "Oh what a beautiful morning",
  "I'm walking on sunshine",
  "You're the sunshine of my life",
  "Somewhere over the rainbow",
  "I can see clearly now the rain is gone",
  "Have you ever seen the rain?",
  "Raindrops keep falling on my head",
  "I'm singing in the rain",
  "Rainy days and Mondays always get me down",
  "Can't stand the rain",
  "Rainy night in Georgia",
  "The moon is made of green cheese",
  "garbage in, garbage out",
  "I'm a lumberjack and I'm OK",
  "I'm a little teapot",
  "I'm a pepper, you're a pepper",
];

const possibleReactions = [
  "😀",
  "😂",
  "😎",
  "😍",
  "😡",
  "🤬",
  "🤪",
  "🤯",
  "🤩",
  "🤮",
  "🤢",
  "🤑",
  "🤓",
  "🤠",
  "🤡",
  "🤥",
  "🤫",
  "🤭",
  "🧐",
  "🧑‍🎄",
  "🧑‍🚀",
  "🧑‍🚒",
  "🧑‍🦯",
  "🧑‍🦰",
  "🧑‍🦱",
  "🧑‍🦲",
  "🧑‍🦳",
  "🧑‍🦼",
  "🧑‍🦽",
  "🧑‍🦼",
  "🧑‍🦽",
  "🧑‍🦯",
];

const genRandomIndex = (arr) => Math.floor(Math.random() * arr.length);

const getRandom = (arr) => arr[Math.floor(Math.random() * arr.length)];

const getRandomUserName = () =>
  `${getRandom(userNames)}${Math.floor(Math.random() * 10 + 1)}`;

const getRandomThought = () => getRandom(thoughts);

const getRandomReaction = () => getRandom(possibleReactions);

module.exports = {
  genRandomIndex,
  getRandomUserName,
  getRandomThought,
  getRandomReaction,
};
